"""aktualizacja bazy danych

Revision ID: 6e60772a485d
Revises: 8fc51de0ca87
Create Date: 2025-10-05 14:55:51.995242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e60772a485d'
down_revision: Union[str, Sequence[str], None] = '8fc51de0ca87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('award_scopes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('award_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('lucide_icon', sa.String(length=100), nullable=True),
    sa.Column('custom_icon_path', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('is_system_award', sa.Boolean(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('icon_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_types_created_by_user_id'), 'award_types', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_award_types_id'), 'award_types', ['id'], unique=False)
    op.create_index(op.f('ix_award_types_name'), 'award_types', ['name'], unique=True)
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('clip_type', sa.Enum('VIDEO', 'SCREENSHOT', name='cliptype'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_clips_id'), 'clips', ['id'], unique=False)
    op.create_index(op.f('ix_clips_uploader_id'), 'clips', ['uploader_id'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('award_name', sa.String(length=100), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clip_id', 'user_id', 'award_name', name='uq_clip_user_award')
    )
    op.create_index(op.f('ix_awards_clip_id'), 'awards', ['clip_id'], unique=False)
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_index(op.f('ix_awards_user_id'), 'awards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_awards_user_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_clip_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_clips_uploader_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_award_types_name'), table_name='award_types')
    op.drop_index(op.f('ix_award_types_id'), table_name='award_types')
    op.drop_index(op.f('ix_award_types_created_by_user_id'), table_name='award_types')
    op.drop_table('award_types')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
