"""Add icon_path and created_by_user_id to AwardType

Revision ID: 8fc51de0ca87
Revises: 635df96c440d
Create Date: 2025-10-04 13:02:10.064768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc51de0ca87'
down_revision: Union[str, Sequence[str], None] = '635df96c440d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_types', sa.Column('icon_path', sa.String(length=500), nullable=True))
    op.add_column('award_types', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_award_types_created_by_user_id'), 'award_types', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_award_types_created_by_user_id'), table_name='award_types')
    op.drop_column('award_types', 'created_by_user_id')
    op.drop_column('award_types', 'icon_path')
    # ### end Alembic commands ###
